name: HyperExecute-Failfast

on:
  schedule:
    - cron: '30 2 * * 1'  # Runs every Monday at 8:00 AM IST
  workflow_dispatch:
    inputs:
      username:
        description: "LT Username (Overrides default secret)"
        required: false
      accessKey:
        description: "LT Access Key (Overrides default secret)"
        required: false
      sampleRepoLink:
        description: "Link to the HyperExecute sample repo"
        default: "https://github.com/john190501/hyperexecute-failfast"
        required: true

jobs:
  HyperExecute-Failfast:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Credentials
        run: |
          echo "Setting up credentials..."

          # If the username input is provided, use it; otherwise, use the secret
          if [ -z "${{ github.event.inputs.username }}" ]; then
            echo "LT_USERNAME=${{ secrets.LT_USERNAME }}" >> $GITHUB_ENV
          else
            echo "LT_USERNAME=${{ github.event.inputs.username }}" >> $GITHUB_ENV
          fi

          # If the accessKey input is provided, use it; otherwise, use the secret
          if [ -z "${{ github.event.inputs.accessKey }}" ]; then
            echo "LT_ACCESS_KEY=${{ secrets.LT_ACCESS_KEY }}" >> $GITHUB_ENV
          else
            echo "LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}" >> $GITHUB_ENV
          fi

          echo "Environment variables set successfully."

      - name: Verify Environment Variables
        run: |
          echo "Verifying credentials..."
          if [ -z "$LT_USERNAME" ]; then
            echo "❌ LT_USERNAME is not set!" && exit 1
          fi
          if [ -z "$LT_ACCESS_KEY" ]; then
            echo "❌ LT_ACCESS_KEY is not set!" && exit 1
          fi
          echo "✅ Credentials verified successfully."

      - name: Download the CLI and Execute the Project
        env:
          LT_USERNAME: ${{ env.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ env.LT_ACCESS_KEY }}
        run: |
          echo "Step 1: Downloading the Sample Project"
          git clone ${{ github.event.inputs.sampleRepoLink }}

          echo "Step 2: Download the HyperExecute CLI"
          cd hyperexecute-failfast
          wget -q https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute
          chmod +x hyperexecute

          echo "Step 3: Execute the Test Suite"
          ./hyperexecute --user "$LT_USERNAME" --key "$LT_ACCESS_KEY" --config yaml/failfast.yaml
